GameShop/config/routes.rb
GameShop::Application.routes.draw do
  devise_for :users
  get "cart/index"
  get "cart/add"
  resources :games

  root :to => "games#index"

  

end

GameShop/app/models/cart.rb
class Cart < ActiveRecord::Base



end

GameShop/app/models/game.rb
class Game < ActiveRecord::Base
end

GameShop/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

GameShop/app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

GameShop/app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

GameShop/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

GameShop/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

GameShop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

GameShop/app/controllers/cart_controller.rb
class CartController < ApplicationController

  def index
    @cart = session[:cart] || {}
  end

  def add
    id = params[:id]
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1

    redirect_to :action => :index
  end

end

GameShop/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :price, :image_url)
    end
end

GameShop/app/helpers/application_helper.rb
module ApplicationHelper
end

GameShop/app/helpers/cart_helper.rb
module CartHelper
end

GameShop/app/helpers/games_helper.rb
module GamesHelper
end

GameShop/app/views/cart/add.html.erb
<h1>Cart#add</h1>
<p>Find me in app/views/cart/add.html.erb</p>

GameShop/app/views/cart/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet2" href="Stylesheet.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="Overview.css">
  <title>GameShop</title>
</head>

<body id="body">

  <div id="wrapper-div">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">GameShop</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', games_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path,method: :delete %></li>
          <% else %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    </nav>

    <h1 class="tabledata"> Your Cart</h1>
    <% sum = 0 %>
    <table>
      <% @cart.each do |id, quantity| %>
          <% game = Game.find(id) %>
          <tr>
            <td><%= image_tag game.image_url, :width => 80 %></td>
            <td class="tabledata" width="250"><%= game.name %></td>
            <td class="tabledata" width="120"><%= quantity %></td>
            <td class="tabledata" width="120"><%= number_to_currency game.price, :unit => "kr" %></td>
            <td class="tabledata" width="120"><%= number_to_currency game.price * quantity, :unit => "kr" %></td>
          </tr>
            <% sum += quantity * game.price %><
      <% end %>
      <tr>
        <td class="tabledata" colspan="4"> Total:</td>
        <td class="tabledata"><%= number_to_currency sum, :unit => "kr" %></td>
      </tr>
    </table>

  </div>

</body>

GameShop/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GameShop/app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

GameShop/app/views/games/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet2" href="Stylesheet.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="Overview.css">
  <title>GameShop</title>
</head>

<body id="body">
  <div id="wrapper-div">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">GameShop</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', games_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path,method: :delete %></li>
          <% else %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>


        </ul>
      </div>
    </nav>

    <form>

      <input id="searchbar" type="text" name="search" placeholder="Search games..">

    </form>

    <div id="sidebar-div">

      <h1>Hello</h1>

    </div>

    <div id="gamebox-wrapper">


      <table id="gamebox-div">
        <thead>

        </thead>

        <tbody>

          <% @games.each do |game| %>
            <div class="gamebox-div">
                <tr>
                  <td><%= image_tag game.image_url %></td>
                  <td>
                    <div id="gamebox-text"><%= game.name %></div>
                    <div class="description"><%= game.description %></div>
                    <div class="linkShow"><%= link_to 'Show', game %></div>
                    <div class="linkEdit"><%= link_to 'Edit', edit_game_path(game) %></div>
                    <div class="linkDestroy"><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                    <td>
                      <div class="price"><%= number_to_currency game.price, :unit => "kr" %></div>
                      <%= link_to 'Add to cart', :controller =>  :cart, :action => :add, :id => game, :class => "btn btn-success" %>

                    </td>
                  </td>
                </tr>
            </div>
          <% end %>

        </tbody>
      </table>

      <br>
      <%= link_to 'New Game', new_game_path %>

    </div>
  </div>
</body>


<br>

GameShop/app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

GameShop/app/views/games/show.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="Overview.css">
  <title>GameShop</title>
</head>

<body id="body">
  <div id="wrapper-div">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">GameShop</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', games_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path,method: :delete %></li>
          <% else %>
              <li><%= link_to 'Shopping cart', cart_index_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    </nav>

    <div id="showgame-box">

      <p id="notice"><%= notice %></p>


      <h1 id="showgame-name"><%= @game.name %></h1>


      <p id="showgame-picture">
        <%= image_tag @game.image_url %>
      </p>

      <p id="showgame-description">
        <strong>Description:</strong>
        <%= @game.description %>
      </p>

      <p id="showgame-price">
        <strong>Price:</strong>
        <%= @game.price %>
      </p>


      <%= link_to 'Edit', edit_game_path(@game) %> |
      <%= link_to 'Back', games_path %>

    </div>


  </div>

</body>

GameShop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameShop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %><div class="alter alert-info"><%= notice %></div><% end %>
<% if alert %><div class="alter alert-warning"><%= alert %></div><% end %>

<%= yield %>

</body>
</html>